server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/person_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: person
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false
    clean-on-validation-error: true
